---
# Elasticsearch Ansible Playbook
- hosts: all
  remote_user: root
  sudo: yes

  vars_files:
    - defaults/main.yml
    - vars/my-vars.yml

  tasks:
    - include: tasks/main.yml
    # Uncomment to install and enable SPM. Make sure to set the spm_client_token variable in your inventory.ini to your SPM key
    # - include: tasks/spm.yml
