---
# Common Tasks

# Install dependencies
- name: Install dependencies
  apt: pkg={{ item }} state=present
  with_items: common_dependencies
  when: ansible_os_family == "Debian"
# Install dependencies
- name: Install dependencies yum
  yum: pkg={{ item }} state=present
  with_items: common_dependencies
  when: ansible_os_family == "RedHat"

# Accept Oracle license
- name: Accept Oracle license prior JDK installation
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections; echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections creates=/usr/lib/jvm/java-7-oracle
  when: ansible_os_family == "Debian"

# Install Java on Debian
- name: Install java on debian
  apt: pkg=oracle-java7-installer state=present
  when: ansible_os_family == "Debian"

# Install Java on RedHat
# TODO: update the jdk version
- name: Download and install oracle jdk
  shell: "creates='~/jdk-7u60-linux-x64.rpm' curl -LO http://download.oracle.com/otn-pub/java/jdk/7u60-b19/jdk-7u60-linux-x64.rpm -H 'Cookie: oraclelicense=accept-securebackup-cookie' ; rpm -i jdk-7u60-linux-x64.rpm"
  when: ansible_os_family == "RedHat"
  ignore_errors: yes